Update integration_delivery.yml

diff --git a/.github/workflows/integration_delivery.yml b/.github/workflows/integration_delivery.yml
--- a/.github/workflows/integration_delivery.yml
+++ b/.github/workflows/integration_delivery.yml
@@ -9,240 +9,240 @@ env:
   PYTHON_VERSION: '3.11.9'
 
 jobs:
-  # dependencies:
-  #   name: Install Dependencies
-  #   runs-on: blacksmith
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       name: Checkout
+  dependencies:
+    name: Install Dependencies
+    runs-on: blacksmith
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout
 
-  #     - name: System Dependencies
-  #       run: |
-  #         sudo apt-get update -y
-  #         sudo apt-get install -y portaudio19-dev
+      - name: System Dependencies
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y portaudio19-dev
 
-  #     - name: Load Cached Poetry
-  #       id: cached-poetry
-  #       uses: actions/cache@v4
-  #       with:
-  #         path: |
-  #           ~/.cache
-  #           ~/.local
-  #         key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+      - name: Load Cached Poetry
+        id: cached-poetry
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cache
+            ~/.local
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
-  #     - uses: actions/setup-python@v5
-  #       name: Setup Python
-  #       with:
-  #         python-version: ${{ env.PYTHON_VERSION }}
-  #         architecture: x64
+      - uses: actions/setup-python@v5
+        name: Setup Python
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          architecture: x64
 
-  #     - name: Install Poetry
-  #       uses: snok/install-poetry@v1
-  #       with:
-  #         virtualenvs-create: true
+      - name: Install Poetry
+        uses: snok/install-poetry@v1
+        with:
+          virtualenvs-create: true
 
-  #     - name: Install dependencies
-  #       run: poetry install --extras=dev --with dev
+      - name: Install dependencies
+        run: poetry install --extras=dev --with dev
 
-  # type-check:
-  #   name: Type Check
-  #   needs:
-  #     - dependencies
-  #   runs-on: blacksmith
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       name: Checkout
+  type-check:
+    name: Type Check
+    needs:
+      - dependencies
+    runs-on: blacksmith
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout
 
-  #     - uses: actions/setup-python@v5
-  #       name: Setup Python
-  #       with:
-  #         python-version: ${{ env.PYTHON_VERSION }}
-  #         architecture: x64
+      - uses: actions/setup-python@v5
+        name: Setup Python
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          architecture: x64
 
-  #     - name: Load Cached Poetry
-  #       id: cached-poetry
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           ~/.cache
-  #           ~/.local
-  #         key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+      - name: Load Cached Poetry
+        id: cached-poetry
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            ~/.cache
+            ~/.local
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
-  #     - name: Create stub files
-  #       run: poetry run pyright --createstub kivy
+      - name: Create stub files
+        run: poetry run pyright --createstub kivy
 
-  #     - name: Type Check
-  #       run: poetry run poe typecheck
+      - name: Type Check
+        run: poetry run poe typecheck
 
-  # lint:
-  #   name: Lint
-  #   needs:
-  #     - dependencies
-  #   runs-on: blacksmith
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       name: Checkout
+  lint:
+    name: Lint
+    needs:
+      - dependencies
+    runs-on: blacksmith
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout
 
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: ${{ env.PYTHON_VERSION }}
-  #         architecture: x64
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          architecture: x64
 
-  #     - name: Load Cached Poetry
-  #       id: cached-poetry
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           ~/.cache
-  #           ~/.local
-  #         key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+      - name: Load Cached Poetry
+        id: cached-poetry
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            ~/.cache
+            ~/.local
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
-  #     - name: Lint
-  #       run: poetry run poe lint
+      - name: Lint
+        run: poetry run poe lint
 
-  # test:
-  #   name: Test
-  #   needs:
-  #     - dependencies
-  #   runs-on: blacksmith
-  #   environment:
-  #     name: test
-  #     url: https://app.codecov.io/gh/${{ github.repository }}/
-  #   steps:
-  #     - name: System Dependencies
-  #       run: |
-  #         sudo apt-get update -y
-  #         sudo apt-get install -y libegl1 libgl1 libmtdev1 libzbar0
+  test:
+    name: Test
+    needs:
+      - dependencies
+    runs-on: blacksmith
+    environment:
+      name: test
+      url: https://app.codecov.io/gh/${{ github.repository }}/
+    steps:
+      - name: System Dependencies
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y libegl1 libgl1 libmtdev1 libzbar0
 
-  #     - uses: actions/checkout@v4
-  #       name: Checkout
+      - uses: actions/checkout@v4
+        name: Checkout
 
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v5
-  #       with:
-  #         python-version: ${{ env.PYTHON_VERSION }}
-  #         architecture: x64
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          architecture: x64
 
-  #     - name: Load Cached Poetry
-  #       uses: actions/cache/restore@v4
-  #       id: cached-poetry
-  #       with:
-  #         path: |
-  #           ~/.cache
-  #           ~/.local
-  #         key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+      - name: Load Cached Poetry
+        uses: actions/cache/restore@v4
+        id: cached-poetry
+        with:
+          path: |
+            ~/.cache
+            ~/.local
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
-  #     - name: Run Tests
-  #       run: |
-  #         mkdir -p $HOME/.kivy/mods
-  #         POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=true poetry run poe test --make-screenshots --cov-report=xml --cov-report=html -n auto --log-level=DEBUG
+      - name: Run Tests
+        run: |
+          mkdir -p $HOME/.kivy/mods
+          POETRY_VIRTUALENVS_OPTIONS_SYSTEM_SITE_PACKAGES=true poetry run poe test --make-screenshots --cov-report=xml --cov-report=html -n auto --log-level=DEBUG
 
-  #     - name: Collect Window Screenshots
-  #       uses: actions/upload-artifact@v4
-  #       if: always()
-  #       with:
-  #         name: screenshots
-  #         path: tests/**/results/**/*.png
+      - name: Collect Window Screenshots
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: screenshots
+          path: tests/**/results/**/*.png
 
-  #     - name: Collect Store Snapshots
-  #       uses: actions/upload-artifact@v4
-  #       if: always()
-  #       with:
-  #         name: snapshots
-  #         path: tests/**/results/**/*.jsonc
+      - name: Collect Store Snapshots
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: snapshots
+          path: tests/**/results/**/*.jsonc
 
-  #     - name: Collect HTML Coverage Report
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: coverage-report
-  #         path: htmlcov
+      - name: Collect HTML Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report
+          path: htmlcov
 
 
-  # build:
-  #   name: Build
-  #   needs:
-  #     - dependencies
-  #   runs-on: blacksmith
-  #   outputs:
-  #     version: ${{ steps.extract-version.outputs.VERSION }}
-  #     name: ${{ steps.extract-version.outputs.NAME }}
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       name: Checkout
-  #       with:
-  #         lfs: true
+  build:
+    name: Build
+    needs:
+      - dependencies
+    runs-on: blacksmith
+    outputs:
+      version: ${{ steps.extract-version.outputs.VERSION }}
+      name: ${{ steps.extract-version.outputs.NAME }}
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout
+        with:
+          lfs: true
 
-  #     - uses: actions/setup-python@v5
-  #       name: Setup Python
-  #       with:
-  #         python-version: ${{ env.PYTHON_VERSION }}
-  #         architecture: x64
+      - uses: actions/setup-python@v5
+        name: Setup Python
+        with:
+          python-version: ${{ env.PYTHON_VERSION }}
+          architecture: x64
 
-  #     - name: Load Cached Poetry
-  #       id: cached-poetry
-  #       uses: actions/cache/restore@v4
-  #       with:
-  #         path: |
-  #           ~/.cache
-  #           ~/.local
-  #         key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
+      - name: Load Cached Poetry
+        id: cached-poetry
+        uses: actions/cache/restore@v4
+        with:
+          path: |
+            ~/.cache
+            ~/.local
+          key: poetry-${{ hashFiles('poetry.lock') }}-${{ env.PYTHON_VERSION}}
 
-  #     - name: Extract Version
-  #       id: extract-version
-  #       run: |
-  #         echo "VERSION=$(poetry version --short)" >> "$GITHUB_OUTPUT"
-  #         echo "NAME=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
-  #         echo "VERSION=$(poetry version --short)"
-  #         echo "NAME=$(poetry version | cut -d' ' -f1)"
+      - name: Extract Version
+        id: extract-version
+        run: |
+          echo "VERSION=$(poetry version --short)" >> "$GITHUB_OUTPUT"
+          echo "NAME=$(poetry version | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"
+          echo "VERSION=$(poetry version --short)"
+          echo "NAME=$(poetry version | cut -d' ' -f1)"
 
-  #     - name: Extract Version from CHANGELOG.md
-  #       run: |
-  #         VERSION_CHANGELOG=$(sed -n '3 s/## Version //p' CHANGELOG.md) 
-  #         echo "VERSION_CHANGELOG=$VERSION_CHANGELOG"
-  #         if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_CHANGELOG" ]; then
-  #           echo "Error: Version extracted from CHANGELOG.md does not match the version in pyproject.toml"
-  #           exit 1 
-  #         else
-  #           echo "Versions are consistent."
-  #         fi
+      - name: Extract Version from CHANGELOG.md
+        run: |
+          VERSION_CHANGELOG=$(sed -n '3 s/## Version //p' CHANGELOG.md) 
+          echo "VERSION_CHANGELOG=$VERSION_CHANGELOG"
+          if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_CHANGELOG" ]; then
+            echo "Error: Version extracted from CHANGELOG.md does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
 
-  #     - name: Extract Version from Tag
-  #       if: startsWith(github.ref, 'refs/tags/v')
-  #       run: |
-  #         VERSION_TAG=$(sed 's/^v//' <<< ${{ github.ref_name }})
-  #         echo "VERSION_TAG=$VERSION_TAG"
-  #         if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_TAG" ]; then
-  #           echo "Error: Version extracted from tag does not match the version in pyproject.toml"
-  #           exit 1 
-  #         else
-  #           echo "Versions are consistent."
-  #         fi
+      - name: Extract Version from Tag
+        if: startsWith(github.ref, 'refs/tags/v')
+        run: |
+          VERSION_TAG=$(sed 's/^v//' <<< ${{ github.ref_name }})
+          echo "VERSION_TAG=$VERSION_TAG"
+          if [ "${{ steps.extract-version.outputs.VERSION }}" != "$VERSION_TAG" ]; then
+            echo "Error: Version extracted from tag does not match the version in pyproject.toml"
+            exit 1 
+          else
+            echo "Versions are consistent."
+          fi
 
-  #     - name: Build
-  #       run: poetry build
+      - name: Build
+        run: poetry build
 
-  #     - name: Upload wheel
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: wheel
-  #         path: dist/*.whl
-  #         if-no-files-found: error
+      - name: Upload wheel
+        uses: actions/upload-artifact@v4
+        with:
+          name: wheel
+          path: dist/*.whl
+          if-no-files-found: error
 
-  #     - name: Upload binary
-  #       uses: actions/upload-artifact@v4
-  #       with:
-  #         name: binary
-  #         path: dist/*.tar.gz
-  #         if-no-files-found: error
+      - name: Upload binary
+        uses: actions/upload-artifact@v4
+        with:
+          name: binary
+          path: dist/*.tar.gz
+          if-no-files-found: error
 
   images:
     name: Create Images
-    # needs:
-    #   - type-check
-    #   - lint
-    #   - test
-    #   - build
+    needs:
+      - type-check
+      - lint
+      - test
+      - build
     runs-on: blacksmith
     container:
       image: mkaczanowski/packer-builder-arm
